export const IF_SHOW_SEARCH="IF_SHOW_SEARCH";
export const FILL_ALL_USERS="FILL_ALL_USERS";
export const REFRESH_RESULT="REFRESH_RESULT";
export const SELECTED_USER="SELECTED_USER";
export const NO_SELECTED_USER="SELECTED_USER";
export const DELETE_RESULT_USER="DELETE_RESULT_USER";
export const CHANGE_COLOR_FIRST_NAME="CHANGE_COLOR_FIRST_NAME";
export const CHANGE_COLOR_LAST_NAME="CHANGE_COLOR_LAST_NAME";
export const SING_IN="SING_IN";
export const SING_UP="SING_UP";
export const SING_OUT="SING_OUT";
export const IF_EXIST="IF_EXIST";
export const IF_ERROR_IN_ADD="IF_ERROR_IN_ADD";

//////////////BUSINESS////////////////////
export const FILL_ALL_BUSINESS="FILL_ALL_BUSINESS";
export const REFRESH_RESULT_BUSINESS="REFRESH_RESULT_BUSINESS";
export const SELECTED_BUSINESS="SELECTED_BUSINESS";
export const DELETE_RESULT_BUSINESS="DELETE_RESULT_BUSINESS";
export const CHANGE_COLOR_NAME="CHANGE_COLOR_NAME";
export const UPDATE_BUISNESS="UPDATE_BUISNESS";
