export const IF_SHOW_SEARCH="IF_SHOW_SEARCH";
export const FILL_ALL_USERS="FILL_ALL_USERS";
export const REFRESH_RESULT="REFRESH_RESULT";
export const SELECTED_USER="SELECTED_USER";
export const NO_SELECTED_USER="SELECTED_USER";
export const DELETE_RESULT_USER="DELETE_RESULT_USER";
export const CHANGE_COLOR_FIRST_NAME="CHANGE_COLOR_FIRST_NAME";
export const CHANGE_COLOR_LAST_NAME="CHANGE_COLOR_LAST_NAME";